application:
  name: file-monitor

chain:
  config:
    yml:
      path: chain/chain-config.yml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33060/TEMP_DB_1
    username: TEMP_DB_1_ADMIN
    password: TEMP_DB_1_ADMIN
