catalog:
  - chain: ASCENDING_CHAIN
    commands:
    - GenericCommand1
    - GenericCommand2
    - GenericCommand3
    - GenericCommand4
    - GenericCommand5

  - chain: DESCENDING_CHAIN
    commands:
    - GenericCommand5
    - GenericCommand4
    - GenericCommand3
    - GenericCommand2
    - GenericCommand1
    -
  - chain: VERIFICATION_CHAIN
    commands:
    - BasicVerificationCommand
    - GenericCommand1
    - BasicVerificationCommand
    - GenericCommand2
    - BasicVerificationCommand
    - GenericCommand3
    - BasicVerificationCommand
    - GenericCommand4
    - BasicVerificationCommand
    - GenericCommand5



